add update-latest-release target.

diff --git a/Makefile.am b/Makefile.am
--- a/Makefile.am
+++ b/Makefile.am
@@ -23,3 +23,27 @@ EXTRA_DIST = plug.in
 
 installcheck-local: install
 	test/run-sql-test.sh
+
+update-latest-release:
+	@if test -z "$(OLD_RELEASE)"; then	\
+	  echo "\$$(OLD_RELEASE) is missing";	\
+	  exit 1;				\
+	fi
+	@if test -z "$(OLD_RELEASE_DATE)"; then		\
+	  echo "\$$(OLD_RELEASE_DATE) is missing";	\
+	  exit 1;					\
+	fi
+	@if test -z "$(NEW_RELEASE_DATE)"; then		\
+	  echo "\$$(NEW_RELEASE_DATE) is missing";	\
+	  exit 1;					\
+	fi
+	cd $(top_srcdir) && test -d "misc" ||					\
+	  svn export --force							\
+	  https://cutter.svn.sourceforge.net/svnroot/cutter/cutter/trunk/misc
+	cd $(top_srcdir) &&					\
+	  misc/update-latest-release.rb				\
+	  $(PACKAGE) $(OLD_RELEASE) $(OLD_RELEASE_DATE)		\
+	  $(VERSION) $(NEW_RELEASE_DATE)			\
+	  rpm/fedora/mysql-groonga.spec.in			\
+	  rpm/centos/mysql-groonga.spec.in			\
+	  debian/changelog
